### ISSUE TITLE
uClock Updates

### ISSUE THREAD

**Issue by dsommars** [alexiszbik/clockbox#4]
Unless I'm doing something incorrectly, it appears uClock updates have broken clockbox.  I'm receiving the error below when attempting to do a "verify" compile in Arduino IDE.  Are there plans to update the code to reflect the new way ppqn works?  It's a damn shame, because I just finished building the circuit for testing with an UNO.  It's been a long time since I've really tried to understand Arduino coding, and I was hoping to build this quickly so I can get back to my modular system.  I'm wondering if anyone is working on solving this issue, or if I'm going to have to learn this all over again (and better) so I can make modifications.

Error:
C:\Users\[nope]\AppData\Local\Temp\.arduinoIDE-unsaved2025228-11432-t33n3e.9i6c\sketch_mar28a\sketch_mar28a.ino: In function 'void setup()':
C:\Users\[nope]\AppData\Local\Temp\.arduinoIDE-unsaved2025228-11432-t33n3e.9i6c\sketch_mar28a\sketch_mar28a.ino:51:10: error: 'class umodular::clock::uClockClass' has no member named 'setClock96PPQNOutput'
   uClock.setClock96PPQNOutput(clockOutput96PPQN);
          ^~~~~~~~~~~~~~~~~~~~
C:\Users\[nuh-uh]\AppData\Local\Temp\.arduinoIDE-unsaved2025228-11432-t33n3e.9i6c\sketch_mar28a\sketch_mar28a.ino:52:10: error: 'class umodular::clock::uClockClass' has no member named 'setClock32PPQNOutput'
   uClock.setClock32PPQNOutput(clockOutput32PPQN);
          ^~~~~~~~~~~~~~~~~~~~
C:\Users\[try-again]\AppData\Local\Temp\.arduinoIDE-unsaved2025228-11432-t33n3e.9i6c\sketch_mar28a\sketch_mar28a.ino:53:11: error: 'PPQNResolution' was not declared in this scope
   setPPQN(PPQNResolution resolution)
           ^~~~~~~~~~~~~~
C:\Users\[that's enough!]\AppData\Local\Temp\.arduinoIDE-unsaved2025228-11432-t33n3e.9i6c\sketch_mar28a\sketch_mar28a.ino:53:3: error: 'setPPQN' was not declared in this scope
   setPPQN(PPQNResolution resolution)
   ^~~~~~~

exit status 1

Compilation error: 'class umodular::clock::uClockClass' has no member named 'setClock96PPQNOutput'

Thank you for any feedback.

-Daniel S.

**Comment by alexiszbik** [comment]
Hello !
Yes uClock code has changed, you can try using an older version to make the code work.
Did you try to revert the version of uClock to 1.5 ?
I might take a look today in order to fix it.

**Comment by alexiszbik** [comment]
Ok, I just figured out that clockbox used a prior version of uClock.
I made the change to make it work with uClock 1.5.1
can you confirm the build issues are fixed ?

thanks

**Comment by dsommars** [comment]
Wow.  I'm impressed by, both, your initial response time and time to
address it!  To be honest, I thought contacting you was the longshot, and
figured I'd have to relearn some coding to get it to work or keep working
backward through uClock versions.

I'm at a coffee shop, so it'll be a minute before I'm able to test it with
a board plugged in.  I just tried to Verify it in the IDE without a board
plugged in and it produced the error below.

My intention is to use your code and circuit to take a pulse input from my
modular to set the clock speed for MIDI output.  I want to set a tempo in
my modular system, then sync a digital pedal via MIDI.  I'd use a Make
Noise Tempi or a Mordax Data to set the tempo.  If I get it working, I will
pass whatever changes I made to you and you can add it to your site if
you'd like.

I'll head home in a moment and test it with a genuine Uno plugged in.


Best regards,

-Daniel S.

===========================================================================
C:\Users\80HD\AppData\Local\Temp\.arduinoIDE-unsaved2025229-4008-xlaq9x.l2pe\sketch_mar29a\sketch_mar29a.ino:
In function 'void clockOutput32PPQN(uint32_t)':
C:\Users\80HD\AppData\Local\Temp\.arduinoIDE-unsaved2025229-4008-xlaq9x.l2pe\sketch_mar29a\sketch_mar29a.ino:22:11:
error: invalid type argument of unary '*' (have 'uint32_t {aka long
unsigned int}')
     if ((*tick % ANALOG_SYNC_RATIO ) == 0) {
           ^~~~
C:\Users\80HD\AppData\Local\Temp\.arduinoIDE-unsaved2025229-4008-xlaq9x.l2pe\sketch_mar29a\sketch_mar29a.ino:
In function 'void setup()':
C:\Users\80HD\AppData\Local\Temp\.arduinoIDE-unsaved2025229-4008-xlaq9x.l2pe\sketch_mar29a\sketch_mar29a.ino:52:10:
error: 'class umodular::clock::uClockClass' has no member named
'setClock96PPQNOutput'
   uClock.setClock96PPQNOutput(clockOutput96PPQN);
          ^~~~~~~~~~~~~~~~~~~~
C:\Users\80HD\AppData\Local\Temp\.arduinoIDE-unsaved2025229-4008-xlaq9x.l2pe\sketch_mar29a\sketch_mar29a.ino:53:10:
error: 'class umodular::clock::uClockClass' has no member named
'setClock32PPQNOutput'
   uClock.setClock32PPQNOutput(clockOutput32PPQN);
          ^~~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: invalid type argument of unary '*' (have 'uint32_t {aka
long unsigned int}')
===========================================================================

**Comment by dsommars** [comment]
My mistake on the last update.  I was still using the latest uClock.  I moved to 1.5.1, and got an error.  Once I removed the '*' from Line 22, it compiled.  I'm about to work on my circuit again. :)

Thank you, again, for the quick fix!

-Daniel S.
